# <u>***PROYECTO DE CLASIFICACIÓN LOGÍSTICA 01: Cáncer de mama***</u>

Los datos utilizados son los de la biblioteca [Sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html#sklearn.datasets.load_breast_cancer) de Python

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

# Definimos las variables

cancer = load_breast_cancer()
X = cancer.data                   #  Definimos datos
y = cancer.target                 # Definimos objetivos

In [ ]:
X

# Valores pertenecientes a la variable 'X'
# Visualizamos la matriz 'X' con los valores correspondientes

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
y

# Valores pertenecientes a la variable 'y'
# Visualizamos el vector 'y' con sus valores correspondientes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)

# X_train -> Entrenamiento de los valores de la X
# X_test  -> Testeo de los valores de la X
# y_train -> Entrenamiento de los valores de la y
# y_test  -> Testeo de los valores de la y

# train_test_split -> Divide los valores de X e y en dos partes:
#-> un conjunto de entrenamiento ;
#-> un conjunto de pruebas, de manera aleatoria.
# test_size // train_size, se pone un tanto por ciento de los datos que queremos entrenar.
# random_state=42 -> hace que la aleatoriedad sea predecible, por lo que si ejecuta
# el mismo código con la misma semilla aleatoria, debería obtener los mismos resultados.


In [ ]:
# Entrenamos la dataset con el modelo logístico de regresión

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# Realizamos predicción en el conjunto de prueba usando la funcion predict()

y_pred=logreg.predict(X_test)

In [ ]:
# Evaluamos el rendimiento del modelo utilizando la métrica de precisión (accuracy)

accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9429824561403509


In [ ]:
matriz_confusion = confusion_matrix(y_test, y_pred)
print(matriz_confusion)

# Ha predicho de las positivas = 154 (verdaderos), y 12 (error) // Predice que es cáncer beningno (154)
# Ha predicho de las negativas = 14 (error), y 276 mal // Predice que no es cáncer maligno (276)


# 154 son verdaderos positivos y 12 falsos positivos(error)
# 14 son falsos negativos(error) y 276 son verdaderos negativos

[[154  12]
 [ 14 276]]


In [ ]:
# Intenta equilibrar ambas métricas y es más útil que la precisión cuando tienes una distribución de clases desequilibrada
logreg.score(X_test, y_test)

0.9429824561403509

# <u>***PROYECTO DE CLASIFICACIÓN LOGÍSTICA 02: Vino***</u>

In [ ]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

wine = load_wine()
X = wine.data
y = wine.target

In [ ]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = logreg.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9722222222222222


In [ ]:
matriz_confusion = confusion_matrix(y_test, y_pred)
print(matriz_confusion)

[[10  2]
 [ 8  8]]


# <u>***PROYECTO DE CLASIFICACIÓN LOGÍSTICA 03:  Digits***</u>

In [ ]:
# Importamos las librerias y sublibrerias necesaria para crear el regreso logico

from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

# Definimos las variables

digits = load_digits()
X = digits.data
y = digits.target

In [ ]:
X

# Valores pertenecientes a la variable 'X'
# La X siempre es una matriz


array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
y


# Valores pertenecientes a la variable 'X'
# La X siempre es una matriz

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
# Entrenamos las variables con los valores

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)

# X_train = Entrenamiento de los valores de la X
# X_test = Testeo de los valores de la X
# y_train = Entrenamiento de los valores de la y
# y_test = Testeo de los valores de la y

# train_test_split = Divide los valores de X e y en dos partes:
# un conjunto de entrenamiento y un conjunto de pruebas, de manera aleatoria.
# test_size // train_size, se pone un tanto por ciento de los datos que queremos entrenar.
# random_state=42 - Siempre se pone de la misma manera

In [ ]:
# Entrenamos la dataset con el modelo logístico de regresión

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# Realizamos prediccion en el conjunto de prueba usando la funcion predict()

y_pred=logreg.predict(X_test)

In [ ]:
# Evaluamos el rendimiento del modelo utilizando la métrica de precisión (accuracy)

accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9443671766342142


In [ ]:
matriz_confusion = confusion_matrix(y_test, y_pred)
print(matriz_confusion)

[[131   0   0   0   0   3   0   0   0   0]
 [  0 130  10   0   1   1   0   0   2   0]
 [  0   2 141   0   0   0   0   0   1   0]
 [  1   0   2 128   0   0   0   0  14   2]
 [  0   1   0   0 136   0   0   2   0   1]
 [  0   1   0   0   0 144   1   0   0   3]
 [  2   1   0   0   1   0 146   0   0   0]
 [  0   0   0   0   1   0   0 146   0   2]
 [  0   7   2   0   0   5   0   0 120   1]
 [  0   2   0   0   0   1   0   4   3 136]]


In [ ]:
logreg.score(X_test, y_test)

0.9443671766342142

In [ ]:
data = load_digits()
list(data.target_names)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# <u>***PROYECTO DE CLASIFICACIÓN LOGÍSTICA 04:  Bancario***</u>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_excel('bank-additional-full.xlsx')
df

age  job  marital  default  housing  loan  duration  campaign  \
0       56    0        1        0        0     0       261         1   
1       57    1        1        1        0     0       149         1   
2       37    1        1        0        1     0       226         1   
3       40    2        1        0        0     0       151         1   
4       56    1        1        0        0     1       307         1   
...    ...  ...      ...      ...      ...   ...       ...       ...   
41183   73    5        1        0        1     0       334         1   
41184   46    3        1        0        0     0       383         1   
41185   56    5        1        0        1     0       189         2   
41186   44    4        1        0        0     0       442         1   
41187   74    5        1        0        1     0       239         3   

       previous  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0             0           1.1         93994.0          -36.4     4857.0   
1             0           1.1         93994.0          -36.4     4857.0   
2             0           1.1         93994.0          -36.4     4857.0   
3             0           1.1         93994.0          -36.4     4857.0   
4             0           1.1         93994.0          -36.4     4857.0   
...         ...           ...             ...            ...        ...   
41183         0          -1.1         94767.0          -50.8     1028.0   
41184         0          -1.1         94767.0          -50.8     1028.0   
41185         0          -1.1         94767.0          -50.8     1028.0   
41186         0          -1.1         94767.0          -50.8     1028.0   
41187         1          -1.1         94767.0          -50.8     1028.0   

       nr.employed  y  
0           5191.0  0  
1           5191.0  0  
2           5191.0  0  
3           5191.0  0  
4           5191.0  0  
...            ... ..  
41183       4963.6  1  
41184       4963.6  0  
41185       4963.6  0  
41186       4963.6  1  
41187       4963.6  0  

[41188 rows x 15 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# X = df.loc[:, df.columns != 'y']
# y = df.y

X = df.iloc[:,:-1]
y = df.y

In [ ]:
X

age  job  marital  default  housing  loan  duration  campaign  \
0       56    0        1        0        0     0       261         1   
1       57    1        1        1        0     0       149         1   
2       37    1        1        0        1     0       226         1   
3       40    2        1        0        0     0       151         1   
4       56    1        1        0        0     1       307         1   
...    ...  ...      ...      ...      ...   ...       ...       ...   
41183   73    5        1        0        1     0       334         1   
41184   46    3        1        0        0     0       383         1   
41185   56    5        1        0        1     0       189         2   
41186   44    4        1        0        0     0       442         1   
41187   74    5        1        0        1     0       239         3   

       previous  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0             0           1.1         93994.0          -36.4     4857.0   
1             0           1.1         93994.0          -36.4     4857.0   
2             0           1.1         93994.0          -36.4     4857.0   
3             0           1.1         93994.0          -36.4     4857.0   
4             0           1.1         93994.0          -36.4     4857.0   
...         ...           ...             ...            ...        ...   
41183         0          -1.1         94767.0          -50.8     1028.0   
41184         0          -1.1         94767.0          -50.8     1028.0   
41185         0          -1.1         94767.0          -50.8     1028.0   
41186         0          -1.1         94767.0          -50.8     1028.0   
41187         1          -1.1         94767.0          -50.8     1028.0   

       nr.employed  
0           5191.0  
1           5191.0  
2           5191.0  
3           5191.0  
4           5191.0  
...            ...  
41183       4963.6  
41184       4963.6  
41185       4963.6  
41186       4963.6  
41187       4963.6  

[41188 rows x 14 columns]

In [ ]:
y

0        0
1        0
2        0
3        0
4        0
        ..
41183    1
41184    0
41185    0
41186    1
41187    0
Name: y, Length: 41188, dtype: int64

In [ ]:
import numpy as np

# Transformamos los datos de la X en matrices

X2 = np.array(X)
X2

array([[ 5.6000e+01,  0.0000e+00,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+03,  5.1910e+03],
       [ 5.7000e+01,  1.0000e+00,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+03,  5.1910e+03],
       [ 3.7000e+01,  1.0000e+00,  1.0000e+00, ..., -3.6400e+01,
         4.8570e+03,  5.1910e+03],
       ...,
       [ 5.6000e+01,  5.0000e+00,  1.0000e+00, ..., -5.0800e+01,
         1.0280e+03,  4.9636e+03],
       [ 4.4000e+01,  4.0000e+00,  1.0000e+00, ..., -5.0800e+01,
         1.0280e+03,  4.9636e+03],
       [ 7.4000e+01,  5.0000e+00,  1.0000e+00, ..., -5.0800e+01,
         1.0280e+03,  4.9636e+03]])

In [ ]:
# Transformamos la y en un vector

y2 = np.array(y)
y2

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, train_size=0.2, random_state=42)

In [ ]:
logreg = LogisticRegression()
logreg.fit(X2_train, y2_train)

LogisticRegression()

In [ ]:
y2_pred=logreg.predict(X2_test)

In [ ]:
accuracy = accuracy_score(y2_test, y2_pred)
print('Accuracy:', accuracy)

Accuracy: 0.8954811690085278


In [ ]:
matriz_confusion = confusion_matrix(y2_test, y2_pred)
print(matriz_confusion)

[[28703   556]
 [ 2888   804]]


In [ ]:
logreg.score(X2_test, y2_test)

0.8954811690085278

# <u>***PROYECTO DE CLASIFICACIÓN LOGÍSTICA 05:  Titanic***</u>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_excel('titanic_train.xlsx')
df

PassengerId  Pclass  Sex   Age  SibSp  Parch       Fare  Embarked  \
0              1       3    0  22.0      1      0       7.25         0   
1              2       1    1  38.0      1      0  712833.00         1   
2              3       3    1  26.0      0      0    7925.00         0   
3              4       1    1  35.0      1      0      53.10         0   
4              5       3    0  35.0      0      0       8.05         0   
..           ...     ...  ...   ...    ...    ...        ...       ...   
886          887       2    0  27.0      0      0      13.00         0   
887          888       1    1  19.0      0      0      30.00         0   
888          889       3    1  29.0      1      2      23.45         0   
889          890       1    0  26.0      0      0      30.00         1   
890          891       3    0  32.0      0      0       7.75         2   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 9 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

X = df.loc[:, df.columns != 'Survived']
y = df['Survived']

In [ ]:
X

PassengerId  Pclass  Sex   Age  SibSp  Parch       Fare  Embarked
0              1       3    0  22.0      1      0       7.25         0
1              2       1    1  38.0      1      0  712833.00         1
2              3       3    1  26.0      0      0    7925.00         0
3              4       1    1  35.0      1      0      53.10         0
4              5       3    0  35.0      0      0       8.05         0
..           ...     ...  ...   ...    ...    ...        ...       ...
886          887       2    0  27.0      0      0      13.00         0
887          888       1    1  19.0      0      0      30.00         0
888          889       3    1  29.0      1      2      23.45         0
889          890       1    0  26.0      0      0      30.00         1
890          891       3    0  32.0      0      0       7.75         2

[891 rows x 8 columns]

In [ ]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
import numpy as np

X2 = np.array(X)
X2

array([[1.00000e+00, 3.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        7.25000e+00, 0.00000e+00],
       [2.00000e+00, 1.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        7.12833e+05, 1.00000e+00],
       [3.00000e+00, 3.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        7.92500e+03, 0.00000e+00],
       ...,
       [8.89000e+02, 3.00000e+00, 1.00000e+00, ..., 2.00000e+00,
        2.34500e+01, 0.00000e+00],
       [8.90000e+02, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.00000e+01, 1.00000e+00],
       [8.91000e+02, 3.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        7.75000e+00, 2.00000e+00]])

In [ ]:
y2 = np.array(y)
y2

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [ ]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.25, random_state=42)

In [ ]:
logreg=LogisticRegression()
logreg.fit(X2_train, y2_train)

LogisticRegression()

In [ ]:
y_pred=logreg.predict(X2_test)

In [ ]:
accuracy=accuracy_score(y2_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.6278026905829597


In [ ]:
matriz_confusion = confusion_matrix(y2_test, y_pred)
print(matriz_confusion)

[[117  17]
 [ 66  23]]
